feat: PageWrapService and PageComponent-decorator
NathanWalker/angular-seed-advanced pull request #247
Opened 2016-09-26 15:52 UTC by m-abs

* Adds the `PageComponent` Decoraator that injects the new class PageWrapService
* Adds `PageWrapService` and `TNSPageWrapService` for getting the page-object
  for the current page, which is injected by Angular Native's `page-router-outlet`

I've removed the `customDecoratorMetadata.directives` from `DecoratorUtils` since after `NgModule` was introducted the `@Component`-decorator no longer takes an `directives`-array.
I've replaced it with an `providers`-array, since `NgModule` makes providers implicitly singleton and we need the current page-object created and injected by Angular Native's `page-router-outlet`.

I'm not sure about adding the PageWrapService to the `Config`-class and replacing it at boottime in {N}, but I couldn't figure out a better way to do it.

2016-09-26 21:42 UTC, NathanWalker commented
Hi @m-abs great work on this. Handy.
I however prefer using `OpaqueTokens` for this sort of thing, just requires less code and provides the user with a simple injectable wherever they need with no need for custom decorator...

Example:

* Add: `src/client/app/frameworks/core/tokens.ts`

Add the following:
```
import {OpaqueToken} from '@angular/core';

export const PAGE: OpaqueToken = new OpaqueToken('page');
```

* Add: `src/client/app/tokens.web.ts`:

```
import {PAGE} from './app/frameworks/core/tokens';

export const TOKENS_WEB: Array<any> = [
  { provide: PAGE, useValue: {} }
];
```

* Add: `nativescript/app/tokens.native.ts`:

```
import {PAGE} from './app/frameworks/core/tokens';
import {topmost} from 'ui/frame';

export const TOKENS_NATIVE: Array<any> = [
  { provide: PAGE, useFactory: () => {
      const frame = topmost();
        if (frame) {
          return frame.currentPage;
        } else {
          return null;
        }
     } 
  }
];
```

## Web

Then you can use that in your web module:

```
@NgModule({
  // etc.,
  providers: [
    TOKENS_WEB
  ],
  // etc.
})
export class WebModule { }
```

## NativeScript

Then you can use in native module:

```
@NgModule({
  // etc.,
  providers: [
    TOKENS_NATIVE
  ],
  // etc.
})
export class NativeModule { }
```

## Usage

This allows users to simply do this wherever they need it:

```
import {PAGE} from '../frameworks/core/tokens';

@Component({
  moduleId: module.id,
  selector: 'sd-sample',
  templateUrl: 'sample.component.html'
})
export class SampleComponent {

  constructor(@Inject(PAGE) private page: any) {
    page. backgroundSpanUnderStatusBar = true;
  }
}
```

👍

2016-09-27 08:23 UTC, m-abs commented
Hi @NathanWalker,

I had consider doing it like that, but when the `component`'s constructor is called `topmost().currentPage` is still the old page-object, because navigation to the page hasn't finished yet.

So I think we'd end up in this situation: https://github.com/NativeScript/nativescript-angular/issues/97

2016-09-27 17:55 UTC, NathanWalker commented
@m-abs Interesting. I wonder if we could provide the `ui/page` `Page` class in the token to circumvent?

2016-09-27 18:03 UTC, NathanWalker commented
Perhaps by using `useValue`, assuming that would get the right value on injection, this may work:

```
import {Page} from 'ui/page';

export const TOKENS_NATIVE: Array<any> = [
  { provide: PAGE, useFactory: () => Page }
];
```

Using `useFactory`, I wonder if it would get the correct `Page` which is being created by the crafty things they are doing here?
https://github.com/NativeScript/nativescript-angular/blob/master/nativescript-angular/router/page-router-outlet.ts#L177-L180

2016-09-28 07:47 UTC, m-abs commented
I was thinking.
In my suggestion I add the `PageWrapperService`-class to `Config`, what if I add the `Page`-class instead and use `Config.Page` as the type in the Component-class?

It isn't pretty, but it's prettier and much less code than my origin PR.

2016-09-28 20:05 UTC, STHanlon commented
@NathanWalker  Not sure if it helps - but I gave the "Page in the token via useFactory" a try. After injection into a component, the page object is undefined.

But - I really like the idea of using OpaqueTokens. Just need to figure out how to get the right Page object. All these hoops just to hide the ActionBar!

2016-09-28 23:47 UTC, NathanWalker requested changes

2016-09-28 23:47 UTC, NathanWalker commented on src/client/app/frameworks/core/decorators/page.component.ts
> +        { provide: PageWrapService, useClass: Config.PageWrapService }
Could you try using an OpaqueToken here?
I have a feeling that the per page token provider would work for page here. If it does then I think we can get rid of `PageWrapService` and `PageComponent` and just provide the page token on `BaseComponent` so any component would have the `PAGE` token to inject at their disposal when needed.

2016-09-30 10:37 UTC, m-abs commented
@NathanWalker 
I tried as you suggested: https://github.com/m-abs/angular2-seed-advanced/tree/add-page-opaquetoken
The factory function is only called once, so I only get first page-object on my component.

I think the PageComponent would be needed.

2016-10-02 02:52 UTC, NathanWalker commented
@m-abs I have some ideas here and wanting to explore on a branch; if they don't go anywhere we will fall back to this!

2016-10-07 17:03 UTC, m-abs commented
Closing in favor of #264

2016-10-07 17:03 UTC, closed without merging